# Generated by Django 5.0.1 on 2024-02-06 16:19

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('five', '0014_userdetails_status_completed_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('user_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('fname', models.CharField(max_length=255)),
                ('lname', models.CharField(max_length=255)),
                ('email_id', models.EmailField(max_length=254, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='userqualifications',
            name='user_details',
        ),
        migrations.CreateModel(
            name='UserCredential',
            fields=[
                ('user_id', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='five.user')),
                ('username', models.CharField(max_length=255)),
                ('password_hash', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Organization',
            fields=[
                ('org_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('org_name', models.CharField(max_length=255)),
                ('org_description', models.TextField()),
                ('org_address', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('org_owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='five.user')),
            ],
        ),
        migrations.CreateModel(
            name='Membership',
            fields=[
                ('membership_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('role_name', models.CharField(choices=[('ADMIN', 'Admin'), ('SURGEON', 'Surgeon'), ('TELERADIOLOGIST', 'Teleradiologist')], default='ADMIN', max_length=20)),
                ('org_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='five.organization')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='five.user')),
            ],
        ),
        migrations.CreateModel(
            name='UserImage',
            fields=[
                ('image_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('image', models.ImageField(upload_to='user_images/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='five.user')),
            ],
        ),
        migrations.CreateModel(
            name='VolumeRecord',
            fields=[
                ('record_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('upload_date', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('UPLOADED', 'Uploaded'), ('QUEUED', 'Queued'), ('PROCESSING', 'Processing'), ('INTERMEDIATE_STATE', 'Intermediate State'), ('COMPLETED', 'Completed')], default='UPLOADED', max_length=20)),
                ('patient_id', models.CharField(max_length=255)),
                ('study_id', models.CharField(max_length=255)),
                ('isAutomated', models.BooleanField(default=False)),
                ('org_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='five.organization')),
                ('uploaded_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='five.user')),
            ],
        ),
        migrations.DeleteModel(
            name='UserDetails',
        ),
        migrations.DeleteModel(
            name='UserQualifications',
        ),
    ]
