# Generated by Django 5.0.1 on 2024-02-15 13:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('five', '0016_rename_email_id_user_email_and_more'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='membership',
            table='app_membership',
        ),
        migrations.AlterModelTable(
            name='organization',
            table='app_organization',
        ),
        migrations.AlterModelTable(
            name='user',
            table='app_user',
        ),
        migrations.AlterModelTable(
            name='usercredential',
            table='app_user_credential',
        ),
        migrations.AlterModelTable(
            name='userimage',
            table='app_user_image',
        ),
        migrations.AlterModelTable(
            name='volumerecord',
            table='app_volume_record',
        ),
    ]
