# Generated by Django 5.0.1 on 2024-02-17 05:24

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('five', '0017_alter_membership_table_alter_organization_table_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='membership',
            name='membership_id',
            field=models.UUIDField(db_column='membership_id', default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='membership',
            name='org_id',
            field=models.ForeignKey(db_column='org_id', on_delete=django.db.models.deletion.CASCADE, to='five.organization'),
        ),
        migrations.AlterField(
            model_name='membership',
            name='role_name',
            field=models.CharField(choices=[('ADMIN', 'Admin'), ('SURGEON', 'Surgeon'), ('TELERADIOLOGIST', 'Teleradiologist')], db_column='role_name', default='ADMIN', max_length=20),
        ),
        migrations.AlterField(
            model_name='membership',
            name='user_id',
            field=models.ForeignKey(db_column='user_id', on_delete=django.db.models.deletion.CASCADE, to='five.user'),
        ),
        migrations.AlterField(
            model_name='organization',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_column='created_at'),
        ),
        migrations.AlterField(
            model_name='organization',
            name='org_address',
            field=models.TextField(db_column='org_address'),
        ),
        migrations.AlterField(
            model_name='organization',
            name='org_description',
            field=models.TextField(db_column='org_description'),
        ),
        migrations.AlterField(
            model_name='organization',
            name='org_id',
            field=models.UUIDField(db_column='org_id', default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='organization',
            name='org_name',
            field=models.CharField(db_column='org_name', max_length=255),
        ),
        migrations.AlterField(
            model_name='organization',
            name='org_owner',
            field=models.ForeignKey(db_column='org_owner_id', on_delete=django.db.models.deletion.CASCADE, to='five.user'),
        ),
        migrations.AlterField(
            model_name='organization',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, db_column='updated_at'),
        ),
        migrations.AlterField(
            model_name='user',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_column='created_at'),
        ),
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(db_column='email', max_length=254, unique=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='first_name',
            field=models.CharField(db_column='first_name', max_length=255),
        ),
        migrations.AlterField(
            model_name='user',
            name='last_name',
            field=models.CharField(db_column='last_name', max_length=255),
        ),
        migrations.AlterField(
            model_name='user',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, db_column='updated_at'),
        ),
        migrations.AlterField(
            model_name='user',
            name='user_id',
            field=models.UUIDField(db_column='user_id', default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='usercredential',
            name='password',
            field=models.CharField(db_column='password', max_length=255),
        ),
        migrations.AlterField(
            model_name='usercredential',
            name='user_id',
            field=models.OneToOneField(db_column='user_id', on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='five.user'),
        ),
        migrations.AlterField(
            model_name='usercredential',
            name='username',
            field=models.CharField(db_column='username', max_length=255),
        ),
        migrations.AlterField(
            model_name='userimage',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_column='created_at'),
        ),
        migrations.AlterField(
            model_name='userimage',
            name='image',
            field=models.ImageField(db_column='image', upload_to='user_images/'),
        ),
        migrations.AlterField(
            model_name='userimage',
            name='image_id',
            field=models.UUIDField(db_column='image_id', default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='userimage',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, db_column='updated_at'),
        ),
        migrations.AlterField(
            model_name='userimage',
            name='user',
            field=models.ForeignKey(db_column='user_id', on_delete=django.db.models.deletion.CASCADE, related_name='images', to='five.user'),
        ),
        migrations.AlterField(
            model_name='volumerecord',
            name='isAutomated',
            field=models.BooleanField(db_column='is_automated', default=False),
        ),
        migrations.AlterField(
            model_name='volumerecord',
            name='org_id',
            field=models.ForeignKey(db_column='org_id', on_delete=django.db.models.deletion.CASCADE, to='five.organization'),
        ),
        migrations.AlterField(
            model_name='volumerecord',
            name='patient_id',
            field=models.CharField(db_column='patient_id', max_length=255),
        ),
        migrations.AlterField(
            model_name='volumerecord',
            name='record_id',
            field=models.UUIDField(db_column='record_id', default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='volumerecord',
            name='status',
            field=models.CharField(choices=[('UPLOADED', 'Uploaded'), ('QUEUED', 'Queued'), ('PROCESSING', 'Processing'), ('INTERMEDIATE_STATE', 'Intermediate State'), ('COMPLETED', 'Completed')], db_column='status', default='UPLOADED', max_length=20),
        ),
        migrations.AlterField(
            model_name='volumerecord',
            name='study_id',
            field=models.CharField(db_column='study_id', max_length=255),
        ),
        migrations.AlterField(
            model_name='volumerecord',
            name='upload_date',
            field=models.DateTimeField(auto_now_add=True, db_column='upload_date'),
        ),
        migrations.AlterField(
            model_name='volumerecord',
            name='uploaded_by',
            field=models.ForeignKey(db_column='uploaded_by_id', on_delete=django.db.models.deletion.CASCADE, to='five.user'),
        ),
    ]
