# Generated by Django 5.0.1 on 2024-02-19 04:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('five', '0019_volumerecord_image_path'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserImage',
        ),
    ]
