# Generated by Django 5.0.1 on 2024-02-19 04:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('five', '0020_delete_userimage'),
    ]

    operations = [
        migrations.RenameField(
            model_name='volumerecord',
            old_name='image_path',
            new_name='volume_meta',
        ),
    ]
