# Generated by Django 5.0.1 on 2024-01-23 14:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('five', '0006_alter_userprofile_name_alter_userprofile_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='age',
            field=models.IntegerField(default=0, null=True),
        ),
    ]
