# Generated by Django 5.0.1 on 2024-01-23 15:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('five', '0007_alter_userprofile_age'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='gender',
            field=models.CharField(default='Not Specified', max_length=10, null=True),
        ),
    ]
