# Generated by Django 5.0.1 on 2024-02-02 09:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('five', '0012_alter_userdetails_gender'),
    ]

    operations = [
        migrations.AddField(
            model_name='userdetails',
            name='step_counter',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='userqualifications',
            name='step_counter',
            field=models.IntegerField(default=0),
        ),
    ]
