# Generated by Django 5.0.1 on 2024-02-03 15:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('five', '0013_userdetails_step_counter_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userdetails',
            name='status_completed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='userqualifications',
            name='status_completed',
            field=models.BooleanField(default=False),
        ),
    ]
