# Generated by Django 5.0.1 on 2024-02-06 16:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('five', '0015_user_remove_userqualifications_user_details_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='email_id',
            new_name='email',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='fname',
            new_name='first_name',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='lname',
            new_name='last_name',
        ),
        migrations.RenameField(
            model_name='usercredential',
            old_name='password_hash',
            new_name='password',
        ),
    ]
